---
dist: trusty
language: node_js
node_js:
  - 8
  - 9
cache:
  directories:
  - node_modules
  - packages/create-react-app/node_modules
  - packages/react-scripts/node_modules
install: true
script:
 - 'if [ $TEST_SUITE = "simple" ]; then tasks/e2e-simple.sh; fi'
 - 'if [ $TEST_SUITE = "kitchensink" ]; then tasks/e2e-kitchensink.sh; fi'
 - 'if [ $TEST_SUITE = "old-node" ]; then tasks/e2e-old-node.sh; fi'
 # Disabled for the moment, since it requires additional work to be done.
 # - 'if [ $TEST_SUITE = "installs" ]; then tasks/e2e-installs.sh; fi'
env:
  matrix:
    - TEST_SUITE=simple
    - TEST_SUITE=kitchensink
    # See comment above
    # - TEST_SUITE=installs
matrix:
  include:
    - node_js: 6
      env: TEST_SUITE=kitchensink